spring.application.name=dobby-core
spring.threads.virtual.enabled=true
spring.config.import=optional:file:.env[.properties]
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
gemini.api.key=${GEMINI_API_KEY}
dobby.bot.url=${DOBBY_BOT_URL}
dobby.security.token=${DOBBY_SECURITY_TOKEN}