# Spring
spring.application.name=dobby-core
spring.threads.virtual.enabled=true
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=dev
server.servlet.context-path=/api/v1

# Logging
management.endpoints.web.exposure.include=logfile
logging.file.name=logs/dobby.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.clean-history-on-start=true

# Spring Swagger UI Docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/openapi.yaml
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true

#Supabase
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.prompt.file=ai_prompt.txt

# Dobby Bot
discord.client.id=${DISCORD_CLIENT_ID}
discord.client.secret=${DISCORD_CLIENT_SECRET}
discord.redirect.uri=${DISCORD_REDIRECT_URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Dev Secret Key
dev.secret.key=${SECERTE_DEV_KEY}

# Frontend
frontend.url=${FRONTEND_URL}

# Backend API key
app.security.api-key-header=${BACKEND_API_HEADER}
app.security.api-key-secret=${BACKEND_API_KEY}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}