spring.application.name=dobby-core
spring.threads.virtual.enabled=true
spring.config.import=optional:file:.env[.properties]
#Supabase
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.prompt.file=ai_prompt.txt
# Dobby Bot
dobby.bot.url=${DOBBY_BOT_URL}
dobby.security.token=${DOBBY_SECURITY_TOKEN}
discord.client.id=${DISCORD_CLIENT_ID}
discord.client.secret=${DISCORD_CLIENT_SECRET}
discord.redirect.uri=${DISCORD_REDIRECT_URI}
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
# Frontend
frontend.url=${FRONTEND_URL}

